### ISSUE TITLE
Consider modularising get_trainer

### ISSUE THREAD

**Issue by samedii** [codewell/ignite-helpers#4]
`get_trainer` takes a single target at the moment. It might be possible to modularise parts of it that are useful even if the use case is not a single target

**Comment by FelixAbrahamsson** [comment]
My idea is that the batch is a json object with arbitrary depth, so targets can contain another dictionary with multiple tensors for example. However, the keys 'features' and 'targets' must always be contained in the root level.

**Comment by samedii** [comment]
Nice, this solves my issue!
